Apps/Curator/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from Apps.Curator.views.general import IndexView, CuratorAccount
from Apps.Curator.views.museums import ExhibitView, AddUnityView, PreviewExhibitView, AddVideoView, AddPDFView, \
    AddURLView, RenderHTTPonHTTPSView
from Apps.Curator.views.opinions import OpinionsView, OpinionDeleterView
from Apps.Curator.views.resources import ResourcesView, NewResourcesView
from Apps.Curator.views.scheduling import SchedulingView, SchedulingExhibitionView

__author__ = "Michel Llorens"
__license__ = "GPL"
__version__ = "1.0.0"
__email__ = "mllorens@dcc.uchile.cl"

from django.conf.urls import url

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^opinions$', OpinionsView.as_view(), name='opinions'),
    url(r'^resources$', ResourcesView.as_view(), name='resources'),
    url(r'^scheduling$', SchedulingView.as_view(), name='scheduling'),
    url(r'^scheduling-exhibition', SchedulingExhibitionView.as_view(), name='scheduling'),
    url(r'^account$', CuratorAccount.as_view(), name='account'),

    url(r'^add-unity-exhibit', AddUnityView.as_view(), name='new-unity'),
    url(r'^add-video-exhibit', AddVideoView.as_view(), name='new-video'),
    url(r'^add-pdf-exhibit', AddPDFView.as_view(), name='new-pdf'),
    url(r'^add-url-exhibit', AddURLView.as_view(), name='new-url'),
    url(r'^iframe-safe', RenderHTTPonHTTPSView.as_view(), name='iframe-safe'),

    url(r'^exhibits', ExhibitView.as_view(), name='exhibits'),
    url(r'^exhibit-preview$', PreviewExhibitView.as_view(), name='exhibit-preview'),

    url(r'^new-resources$', NewResourcesView.as_view(), name='resources'),

    url(r'^timeout_opinions_deleter$', OpinionDeleterView.as_view(), name='deleter'),
]

VirtualMuseumsFramework/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

from Apps.CommonWeb.views import IndexView, ContactView
from Apps.CommonWeb.views import LoginView
from Apps.CommonWeb.views import LogoutView
from Apps.Curator.views.opinions import OpinionHashView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^contact/', ContactView.as_view(), name='contact'),
    url(r'^auth/login', LoginView.as_view(), name='login'),
    url(r'^accounts/login', LoginView.as_view(), name='login'),
    url(r'^auth/logout', LogoutView.as_view(), name='logout'),
    url(r'^confirmation/', OpinionHashView.as_view(), name='opinion_confirmation'),
    url(r'^curator/', include('Apps.Curator.urls')),
    url(r'^visitor/', include('Apps.Visitor.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/museum.ico', permanent=True)),

]

Apps/Curator/models/opinions.py
from __future__ import unicode_literals

from django.db import models


class Opinion(models.Model):
    person_name = models.CharField(max_length=30, blank=False)
    opinion = models.TextField(blank=False)
    status = models.BooleanField(default=False)
    email = models.EmailField(blank=False)
    hash_key = models.TextField()
    validated = models.BooleanField(default=False)
    timeout = models.DateField(blank=False)
    rating = models.IntegerField(default=0)

    exhibit = models.ForeignKey("Exhibit")

    @property
    def avatar(self):
        return "https://api.adorable.io/avatars/285/"+self.person_name+"@adorable.io"

Apps/Curator/models/scheduling.py
from __future__ import unicode_literals

from django.db import models

from Apps.Curator.models.museums import Exhibit


class Exhibition(models.Model):
    name = models.CharField(max_length=30, blank=False)
    status = models.BooleanField(default=False)
    start_date = models.DateField(blank=False)
    end_date = models.DateField(blank=False)

    exhibits = models.ManyToManyField(Exhibit)

Apps/Curator/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from django.forms import Textarea

from Apps.Curator.models.museums import UnityExhibit, VideoExhibit, PDFExhibit, URLExhibit
from Apps.Curator.models.resources import ExternalImage, ExternalTemplate, ExternalMusic, ExternalModel, ExternalVideo

__author__ = "Michel Llorens"
__license__ = "GPL"
__version__ = "1.0.0"
__email__ = "mllorens@dcc.uchile.cl"


class CommonMeta:
    fields = ('title', 'description', 'file',)
    widgets = {
        'description': Textarea(attrs={'cols': 30, 'rows': 5}),
    }


class UnityExhibitMeta:
    fields = {'name', 'memory_to_allocate', 'data', 'javascript', 'memory'}
    labels = {'name': 'Name of exhibit',
              'memory_to_allocate': 'Unity TOTAL_MEMORY',
              'data': 'File exhibit.data',
              'javascript': 'File exhibit.js',
              'memory': 'File exhibit.mem'}


class VideoExhibitMeta:
    fields = {'name', 'video'}
    labels = {'name': 'Name of exhibit',
              'video': 'Video exhibit.(mp4/webm/ogg)'}


class PDFExhibitMeta:
    fields = {'name', 'pdf'}
    labels = {'name': 'Name of exhibit',
              'pdf': 'PDF File'}


class URLExhibitMeta:
    fields = {'name', 'url'}
    labels = {'name': 'Name of exhibit',
              'url': 'URL to be displayed'}


class NewExhibitForm(forms.ModelForm):
    field_order = ['name']


class UnityExhibitForm(forms.ModelForm):
    field_order = ['name', 'memory_to_allocate', 'data', 'javascript', 'memory']

    class Meta(UnityExhibitMeta):
        model = UnityExhibit


class VideoExhibitForm(forms.ModelForm):
    field_order = ['name', 'video']

    class Meta(VideoExhibitMeta):
        model = VideoExhibit


class PDFExhibitForm(forms.ModelForm):
    field_order = ['name', 'pdf']

    class Meta(PDFExhibitMeta):
        model = PDFExhibit


class URLExhibitForm(forms.ModelForm):
    field_order = ['name', 'url']

    class Meta(URLExhibitMeta):
        model = URLExhibit


class TemplateForm(forms.ModelForm):
    class Meta(CommonMeta):
        model = ExternalTemplate


class MusicForm(forms.ModelForm):
    class Meta(CommonMeta):
        model = ExternalMusic


class ImageForm(forms.ModelForm):
    class Meta(CommonMeta):
        model = ExternalImage


class ModelForm(forms.ModelForm):
    class Meta(CommonMeta):
        model = ExternalModel


class VideoForm(forms.ModelForm):
    class Meta(CommonMeta):
        model = ExternalVideo

Apps/Curator/views/general.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView


class IndexView(TemplateView):
    main_url = '/curator/scheduling'

    @method_decorator(login_required(login_url='/auth/login'))
    def get(self, request, *a, **ka):
        return redirect(self.main_url)


class CuratorAccount(TemplateView):
    template_name = 'curator/curator-account.html'

    @method_decorator(login_required(login_url='/auth/login'))
    def get(self, request, *a, **ka):
        return render(request, self.template_name)

    @method_decorator(login_required(login_url='/auth/login'))
    def post(self, request, *a, **ka):
        modifications = {'error': [], 'success': []}
        user = request.user

        fullname = request.POST.get('name', '')
        email = request.POST.get('email', '')

        new_password = request.POST.get('new-password', '')
        confirm_password = request.POST.get('confirm-password', '')

        password = request.POST.get('password', '')

        if len(new_password) > 0:
            if len(confirm_password) > 0\
                    and new_password == confirm_password:
                if len(password) > 0 and user.check_password(password):
                    user.set_password(new_password)
                    modifications['success'].append('Successful password change.')
                else:
                    modifications['error'].append('Incorrect password.')
            else:
                modifications['error'].append('Passwords mismatch.')

        if len(fullname) > 0:
            try:
                first, last = fullname.split(" ", 1)
                user.first_name = first
                user.last_name = last
                modifications['success'].append('Successful name change')
            except ValueError:
                modifications['error'].append('Name must have at least first and last name.')

        if len(email) > 0:
            try:
                validate_email(email)
                user.email = email
                modifications['success'].append('Successful email change')
            except ValidationError:
                modifications['error'].append('Wrong email structure.')

        if len(modifications['error']) != 0:
            modifications['success'] = []
        elif len(modifications['success']) < 1:
            modifications['error'].append('No changes was applied')
        else:
            user.save()
        return render(request, self.template_name, modifications)

Apps/Curator/views/museums.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.generic import TemplateView

from Apps.Curator.decorators import group_required
from Apps.Curator.forms import UnityExhibitForm, NewExhibitForm, VideoExhibitForm, PDFExhibitForm, URLExhibitForm
from Apps.Curator.models.museums import Exhibit, URLExhibit
from Apps.Curator.models.opinions import Opinion
from Apps.Curator.models.scheduling import Exhibition
from Apps.Curator.views.museums_types import MUSEUM_TYPES


@transaction.atomic
def get_exhibit():
    exhibit_dict = {'exhibits': []}

    exhibits = Exhibit.objects.all()

    for exhibit in exhibits:
        exhibition = Exhibition.objects.filter(exhibits=exhibit).filter(status=True)
        published = True if len(exhibition) > 0 else False
        rating_object = Opinion.objects.filter(exhibit=exhibit).filter(validated=True).aggregate(Avg('rating'))
        rating = rating_object['rating__avg']
        if rating is None:
            rating = 0
        exhibit_dict['exhibits'].append({'id': exhibit.id,
                                        'name': exhibit.name,
                                        'published': published,
                                        'visitors': exhibit.visitors,
                                        'rating': rating})
    return exhibit_dict


@transaction.atomic
def delete_exhibit(exhibit_id):
    exhibit = Exhibit.objects.get(id=exhibit_id)

    delete_function = MUSEUM_TYPES[exhibit.exhibit_type.name]['delete'](exhibit_id)

    exhibit.delete()
    delete_function()


class ExhibitView(TemplateView):
    template_name = 'curator/exhibits.html'

    @method_decorator(group_required('Museum_team'))
    @method_decorator(login_required(login_url='/auth/login'))
    def get(self, request, *a, **ka):
        exhibits = get_exhibit()
        return render(request, self.template_name, exhibits)

    @method_decorator(group_required('Museum_team'))
    @method_decorator(login_required(login_url='/auth/login'))
    def post(self, request, *a, **ka):
        exhibit_id = request.POST.get('id_exhibit', None)
        delete = request.POST.get('delete', None)
        preview = request.POST.get('preview', None)

        if exhibit_id is not None:
            if delete in ['1']:
                delete_exhibit(exhibit_id)
            elif preview in ['1']:
                url = '/curator/exhibit-preview?id=' + exhibit_id
                return redirect(url)

        exhibitions = get_exhibit()

        return render(request, self.template_name, exhibitions)


class AddExhibitView(TemplateView):
    template_name = 'curator/add-exhibit.html'
    form = NewExhibitForm
    exhibit_type = ''

    @method_decorator(group_required('Museum_team'))
    @method_decorator(login_required(login_url='/auth/login'))
    def get(self, request, *a, **ka):
        form = self.form()
        parameters = {'form': form, 'exhibit_type': self.exhibit_type}

        return render(request, self.template_name, parameters)

    @method_decorator(group_required('Museum_team'))
    @method_decorator(login_required(login_url='/auth/login'))
    def post(self, request, *a, **ka):
        request_form = self.form(request.POST, request.FILES)
        args = {'exhibit_type': self.exhibit_type}

        if request_form.is_valid():
            request_form.save()
            args['success'] = 'success'
            request_form = self.form()

        args['form'] = request_form

        return render(request, self.template_name, args)


class AddUnityView(AddExhibitView):
    form = UnityExhibitForm
    exhibit_type = 'Unity'


class AddVideoView(AddExhibitView):
    form = VideoExhibitForm
    exhibit_type = 'Video'


class AddPDFView(AddExhibitView):
    form = PDFExhibitForm
    exhibit_type = 'Pdf'


class AddURLView(AddExhibitView):
    form = URLExhibitForm
    exhibit_type = 'Url'


@transaction.atomic
def get_exhibit_data(exhibit_id):
    exhibit = Exhibit.objects.get(id=exhibit_id)
    data = MUSEUM_TYPES[exhibit.exhibit_type.name]['get'](exhibit)
    return data


@transaction.atomic
def get_exhibit_model(exhibit_id):
    return Exhibit.objects.get(id=exhibit_id)


class PreviewExhibitView(TemplateView):

    @method_decorator(group_required('Museum_team'))
    @method_decorator(login_required(login_url='/auth/login'))
    @xframe_options_exempt
    def get(self, request, *a, **ka):
        exhibit_id = request.GET.get('id', None)

        if exhibit_id is None:
            return redirect('/curator')

        exhibit = get_exhibit_model(exhibit_id)
        template = MUSEUM_TYPES[exhibit.exhibit_type.name]['template']

        args = get_exhibit_data(exhibit_id)

        return render(request, template, args)


class RenderHTTPonHTTPSView(TemplateView):

    @method_decorator(group_required('Museum_team'))
    @method_decorator(login_required(login_url='/auth/login'))
    @xframe_options_exempt
    def get(self, request, *a, **ka):
        url_uuid = request.GET.get('uuid', None)

        if url_uuid is None:
            return redirect('/curator')

        exhibit = URLExhibit.objects.filter(uuid=url_uuid).first()

        if exhibit is None:
            return redirect('/curator')

        return redirect(exhibit.url)

Apps/Curator/views/museums_types.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os

from django.db import transaction

from Apps.Curator.models.museums import UnityExhibit, VideoExhibit, PDFExhibit, URLExhibit
from Apps.Curator.views.resources_types import parse_inner_url

__author__ = "Michel Llorens"
__license__ = "GPL"
__version__ = "1.0.0"
__email__ = "mllorens@dcc.uchile.cl"


def delete_unity_files(exhibit_id):
    unity_exhibit = UnityExhibit.objects.get(id=exhibit_id)

    memory = unity_exhibit.memory.path
    javascript = unity_exhibit.javascript.path
    data = unity_exhibit.data.path

    def delete():
        os.remove(memory)
        os.remove(javascript)
        os.remove(data)

    return delete


@transaction.atomic
def get_unity_data(exhibit):
    data = dict()

    data['title'] = exhibit.name
    exhibit = UnityExhibit.objects.get(id=exhibit.id)
    data['data'] = parse_inner_url(exhibit.data.url)
    data['js'] = parse_inner_url(exhibit.javascript.url)
    data['mem'] = parse_inner_url(exhibit.memory.url)
    data['total_memory'] = exhibit.memory_to_allocate

    return data


def delete_video_files(exhibit_id):
    video_exhibit = VideoExhibit.objects.get(id=exhibit_id)

    video = video_exhibit.video.path

    def delete():
        os.remove(video)

    return delete


@transaction.atomic
def get_video_data(exhibit):
    data = dict()

    data['title'] = exhibit.name
    exhibit = VideoExhibit.objects.get(id=exhibit.id)
    data['video'] = parse_inner_url(exhibit.video.url)
    extension = os.path.splitext(data['video'])[1].replace(".", "")
    data['type'] = extension

    return data


def delete_pdf_files(exhibit_id):
    pdf_exhibit = PDFExhibit.objects.get(id=exhibit_id)

    pdf = pdf_exhibit.pdf.path

    def delete():
        os.remove(pdf)

    return delete


@transaction.atomic
def get_pdf_data(exhibit):
    data = dict()

    data['title'] = exhibit.name
    exhibit = PDFExhibit.objects.get(id=exhibit.id)
    data['pdf'] = parse_inner_url(exhibit.pdf.url)

    return data


def delete_url_files(exhibit_id):

    def delete():
        pass

    return delete


@transaction.atomic
def get_url_data(exhibit):
    data = dict()

    data['title'] = exhibit.name
    exhibit = URLExhibit.objects.get(id=exhibit.id)
    data['uuid'] = exhibit.uuid

    return data


MUSEUM_TYPES = {
    'Unity': {'delete': delete_unity_files, 'get': get_unity_data,
              'template': 'curator/preview_exhibits/preview_unity.html'},
    'Video': {'delete': delete_video_files, 'get': get_video_data,
              'template': 'curator/preview_exhibits/preview_video.html'},
    'Pdf': {'delete': delete_pdf_files, 'get': get_pdf_data,
            'template': 'curator/preview_exhibits/preview_pdf.html'},
    'Url': {'delete': delete_url_files, 'get': get_url_data,
            'template': 'curator/preview_exhibits/preview_url.html'}
}

templates/curator/add-museum.html
{% extends "base/base.html" %}

{% block css %}
{% endblock css %}


{% block js %}
{% endblock js %}


{% block body %}
    <body>
    {% include "curator/navbar.html" %}

    <div class="container">
        <h2>Add {{ exhibit_type }} Museum</h2>
        {% if success %}
            <div class="alert alert-success">
                <strong>Success!</strong> The museum was correctly uploaded.
            </div>
        {% endif %}
        <br>
        <div class="jumbotron">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="fieldWrapper">
                                {% if field.errors %}
                                    <div class="alert alert-danger">
                                {% endif %}
                                <div class="form-group row">
                                    <label for="{{ field.id_for_label }}" class="col-md-6 col-form-label">{{ field.label }}:</label>
                                    <div class="col-md-6">
                                        {{ field }}
                                    </div>
                                </div>

                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                                {% if field.errors %}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}

                        <button class="btn btn-sm btn-info" type="submit">Upload museum</button>
                    </form>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>
    </div>
    </body>
{% endblock body %}

templates/curator/curator-account.html
{% extends "base/base.html" %}

{% block css %}
{% endblock css %}


{% block js %}
{% endblock js %}


{% block body %}
<body>
{% include "curator/navbar.html" %}
<div class="container">
    <h2>Account</h2>
    {% for failure in error %}
        <div class="alert alert-danger">
            <strong>Error!</strong> {{ failure }}
        </div>
    {% endfor %}
    {% for hit in success%}
    <div class="alert alert-success">
        <strong>Success!</strong> {{ hit }}
    </div>
    {% endfor %}
    <br>
    <div class="jumbotron">
        {% if user.is_authenticated %}
            <form method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-4">
                        <a class="thumbnail">
                            <img src="https://api.adorable.io/avatars/200/{{ user.get_full_name }}" alt="...">
                        </a>
                    </div>
                    <div class="col-md-4">
                        <h4>Name:</h4>
                        <input type="text" name="name" class="form-control"
                               value="{{ user.get_full_name }}">
                        <h4>Email:</h4>
                        <input type="email" name="email" placeholder="your@email.com" class="form-control"
                               value="{{ user.email }}">
                    </div>
                    <div class="col-md-4">
                        <h4>New password:</h4>
                        <input type="password" name="new-password" class="form-control">
                        <h4>Confirm new password:</h4>
                        <input type="password" name="confirm-password" class="form-control">
                        <h4>Current password:</h4>
                        <input type="password" name="password" class="form-control">
                        <br><br>
                        <button class="btn btn-sm btn-success btn-block" type="submit">Save changes</button>
                    </div>
                </div>
            </form>
        {% endif %}
    </div>
</div>
</body>
{% endblock body %}

templates/curator/exhibits.html
{% extends "base/base.html" %}

{% block css %}
    <link rel="stylesheet" href="/static/bower_components/jquery-bar-rating/dist/themes/bars-square.css">
{% endblock css %}


{% block js %}
    <script src="/static/bower_components/jquery-bar-rating/dist/jquery.barrating.min.js"></script>
{% endblock js %}


{% block body %}
    <body>
    {% include "curator/navbar.html" %}
    <div class="container">
        <h2>Exhibits</h2>
        <br>
        <div class="jumbotron">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>In active exhibitions</th>
                    <th>Visitors</th>
                    <th>Rating</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for exhibit in exhibits %}
                    <tr>
                        <form method="POST" action="/curator/exhibits">
                            {% csrf_token %}
                            <input type="hidden" id="id_exhibition_{{ exhibit.id }}"
                                   name="id_exhibit" value="{{ exhibit.id }}" />
                            <input type="hidden" id="delete_{{ exhibit.id }}" name="delete" value="0" />
                            <input type="hidden" id="preview_{{ exhibit.id }}" name="preview" value="0" />
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ exhibit.name }}</td>
                            <td>{{ exhibit.published }}</td>
                            <td>{{ exhibit.visitors }}</td>
                            <td>
                                <select id="rating_{{ exhibit.id }}">
                                    <option value=""></option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                </select>
                            </td>
                            <td>

                                <button class= "btn btn-sm btn-info" type="button"
                                        onclick="document.getElementById('preview_{{ exhibit.id }}').value='1';
                                                form.submit();">Preview</button>
                                <button class= "btn btn-sm btn-danger" type="button"
                                        onclick="if (confirm('You really want to delete this exhibit') == true) {
                                                document.getElementById('delete_{{ exhibit.id }}').value='1';
                                                form.submit();}">Delete</button>
                            </td>
                        </form>

                        <script type="text/javascript">
                            $(function() {
                                $('#rating_{{ exhibit.id }}').barrating({
                                    theme: 'bars-square',
                                    showValues:true,
                                    readonly:true,
                                    allowEmpty:true,
                                    initialRating: {{ exhibit.rating }},
                                    showSelectedRating:false
                                });
                            });
                        </script>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    </body>
{% endblock body %}

templates/curator/index.html
{% extends "base/base.html" %}

{% block css %}
{% endblock css %}


{% block js %}
{% endblock js %}


{% block body %}
<body>
  {% include "curator/navbar.html" %}
  Curator principal view
</body>
{% endblock body %}

templates/curator/opinions.html
{% extends "base/base.html" %}

{% block css %}
{% endblock css %}


{% block js %}
{% endblock js %}


{% block body %}
    <body>
    {% include "curator/navbar.html" %}
    <div class="container">
        <h2>People's Opinion</h2>
        {% if success %}
            <div class="alert alert-success">
                <strong>Success!</strong> Your action was performed correctly.
            </div>
        {% endif %}
        <form method="POST" action="/curator/opinions" class="form-inline ng-pristine ng-valid">
            {% csrf_token %}
            <label >Select Exhibit: </label>
            <select name="exhibit" class="form-control ng-pristine ng-valid ng-empty ng-touched" onChange="form.submit();">
                <option value="" disabled="" class="" {{ header.selected }}>{{ header.display }}</option>
                {% for element in options %}
                    <option label="{{ element.display }}" value="{{ element.id }}" {{ element.selected }}>
                        {{ element.display }}
                    </option>
                {% endfor %}
            </select>
            <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-primary {% if approved %} active {% endif %}"><input type="checkbox" name="approved" {{ approved }} onChange="form.submit();">Approved</label>
                <label class="btn btn-primary {% if pending %} active {% endif %}"><input type="checkbox" name="pending" {{ pending }} onChange="form.submit();">Pending</label>
            </div>
        </form>
        <br>
        <div>
            {% for opinion in opinions %}

                <div class="jumbotron">
                    <form method="POST" action="/curator/opinions">
                        {% csrf_token %}
                        <input type="hidden" id="id_opinion" name="id_opinion" value="{{ opinion.id }}" />
                        <input type="hidden" id="delete_{{ opinion.id }}" name="delete" value="0" />
                        <input type="hidden" id="reverse_{{ opinion.id }}" name="reverse" value="0" />
                        <input type="hidden" id="exhibit" name="exhibit" value="{{ current_exhibit }}" />
                        {% if approved %}<input type="hidden" id="approved" name="approved" value="1" />{% endif %}
                        {% if pending %}<input type="hidden" id="pending" name="pending" value="1" />{% endif %}
                        <div class="row">
                            <div class="col-md-2">
                                <a class="thumbnail">
                                    <img src="{{ opinion.avatar }}" alt="User avatar">
                                </a>
                                <p class="text-center">{{ opinion.name|escapejs }}</p>
                            </div>
                            <div class="col-md-8">{{ opinion.opinion|escapejs }}</div>
                            <div class="col-md-2">
                                <button class= "btn btn-sm btn-warning btn-block" type="button"
                                        onclick="if (confirm('You really want to change status of this opinion') == true) {
                                                document.getElementById('reverse_{{ opinion.id }}').value = '1'; form.submit();}">
                                    {% if opinion.status == False %}Approve {% else %} Disapprove {% endif %}</button>
                                <button class= "btn btn-sm btn-danger btn-block" type="button"
                                        onclick="if (confirm('You really want to delete this opinion') == true) {
                                                document.getElementById('delete_{{ opinion.id }}').value = '1'; form.submit();}">
                                    Delete</button>
                                <a class="btn btn-sm btn-info btn-block" type="button" href="mailto:{{ opinion.email }}">Send email</a>
                            </div>
                        </div>
                    </form>
                </div>


            {% endfor %}
        </div>
    </div>
    </body>
{% endblock body %}

templates/curator/preview.html
{% extends "base/base.html" %}

{% block css %}
    <link rel="stylesheet" href="/static/common-web/unity/style.css">
{% endblock css %}


{% block js %}
    <script src="/static/common-web/unity/UnityProgress.js"></script>
{% endblock js %}


{% block body %}
    <body>
    <div class="template-wrap clear">
        <canvas class="emscripten" id="canvas" oncontextmenu="event.preventDefault()" height="720px" width="1280px"></canvas>
        <br>
        <div class="logo"></div>
        <div class="fullscreen"><img src="/static/common-web/unity/fullscreen.png" width="38" height="38" alt="Fullscreen" title="Fullscreen" onclick="SetFullscreen(1);" /></div>
        <div class="title">{{ title }}</div>
    </div>
    <p class="footer">&laquo; created with <a href="http://unity3d.com/" title="Go to unity3d.com">Unity</a> &raquo;</p>

    <script type='text/javascript'>
        var Module = {
            TOTAL_MEMORY: {{ total_memory }},
            errorhandler: null,
            compatibilitycheck: null,
            dataUrl: "{{ data }}",
            codeUrl: "{{ js }}",
            memUrl: "{{ mem  }}",

        };
    </script>
    <script src="/static/common-web/unity/UnityLoader.js"></script>
    </body>
{% endblock body %}